# Generated by Django 3.0.5 on 2020-04-11 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_code', models.CharField(max_length=6)),
                ('classroom_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('env', models.CharField(choices=[('J', 'Java'), ('P', 'Python3'), ('C', 'C++')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_of', models.ManyToManyField(related_name='student', to='classroom.Classroom')),
                ('teacher_of', models.ManyToManyField(related_name='teacher', to='classroom.Classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('workspace_template', models.URLField()),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.Classroom')),
            ],
        ),
    ]
