# Generated by Django 3.0.5 on 2020-04-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200411_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsuser',
            name='student_of',
            field=models.ManyToManyField(blank=True, related_name='student', to='classroom.Classroom'),
        ),
        migrations.AlterField(
            model_name='fsuser',
            name='teacher_of',
            field=models.ManyToManyField(blank=True, related_name='teacher', to='classroom.Classroom'),
        ),
    ]
