# Generated by Django 3.0.5 on 2020-04-12 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200412_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsuser',
            name='current_class_ide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.Classroom'),
        ),
        migrations.AddField(
            model_name='fsuser',
            name='current_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
