# Generated by Django 3.0.5 on 2020-04-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200412_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsuser',
            name='current_class_ide',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
