# Generated by Django 3.0.5 on 2020-04-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200412_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsuser',
            name='current_class_ide',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
