# Generated by Django 3.0.5 on 2020-04-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200412_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_by',
            field=models.ManyToManyField(to='classroom.FSUser'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='workspace_template',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
