# Generated by Django 3.0.5 on 2020-04-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_dockerinstances'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='folder_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
