# Generated by Django 3.0.5 on 2020-04-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_assignment_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teacher_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
